export const ACTUALIZAR = 'PUBLICACIONES_ACTUALIZAR';
export const CARGANDO = 'PUBLICACIONES_CARGANDO';
export const ERROR = 'PUBLICACIONES_ERROR';
export const COM_ACTUALIZAR = 'COMENTARIOS_ACTUALIZAR';
export const COM_CARGANDO = 'COMENTARIOS_ERROR';
export const COM_ERROR = 'COMENTARIOS_ERROR';
